---
{{- $secretEnable := $.Values.secret.enabled | default false }}
{{- if $secretEnable}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
