app:
  name: test

deployment:
  replicas: 1
  imageRepo: sdblepas/vim
  imageTag: latest
  imagePullPolicy: Always
  containerPort: 4000
  readinessProbePath: "/test"
  livenessProbePath: "/test"
  envSecret:
    enabled: true
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"

service:
  enabled: true
  port: 80

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hostname: address-book.kube.pm

secret:
  enabled: true
  data:
    secret_name: secret_value
